Repository chromaui/learnstorybook.com, pull requests merged in 2019-10, with the labels that each got.

#156 Add Twitter card meta tag
  src/components/composite/AppLayout.js
Labels: DO NOT MERGE

#91 Creating addons section
  content/intro-to-storybook/index.md
  content/intro-to-storybook/react/en/creating-addons.md
  content/intro-to-storybook/react/en/using-addons.md
  content/intro-to-storybook/react/pt/using-addons.md
  static/intro-to-storybook/design-assets-addon.png
Labels: enhancement

#160 REMOVE typescript from creating-addons.md
  content/intro-to-storybook/react/en/creating-addons.md
Labels: bug

#198 ADD github action && overhaul CI
  .circleci/config.yml
  .github/workflows/chromatic.yml
  .gitignore
  .vscode/settings.json
  package.json
  src/components/composite/MailingListSignup.js
  src/components/screens/GuideScreen/index.js
  yarn.lock
Labels: enhancement
